### ISSUE TITLE
Point mingw-w64.org to this website as well

### ISSUE THREAD

**Issue by lazka** [mingw-w64/mingw-w64.github.io#1]
@adrien-n I've heard that you are the owner of mingw-w64.org. We've set up a new website using a static site generator here (https://www.mingw-w64.net/) Would it be possible to move mingw-w64.org to the same server? If you need any help/info please let us know. We can also transfer ownership, if that is easier.

**Comment by adrien-n** [comment]
Hi,

Sure! Thanks for taking care of this. I'm also still interested in transfering the .org domain itself to someone currently involved in the project if possible.

I'll need some kind of proof for the domain name usage though. Maybe a commit visible from the sourceforge repo that mentions the domaine name(s).

**Comment by elieux** [comment]
Hey.  For the proof, I assume you mean to somehow approve the legitimacy of mingw-w64.net (and by extension, the domain transfer request) by mingw-w64 maintainers.  I'll ask around and let you know here.

**Comment by elieux** [comment]
@adrien-n, we did this: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/7b50e7063d8b5cfb2c9284697e15b18b7e97d875/

If you need any other evidence, don't hesitate to ask.

If you want to start the transfer, tell me whether you have experience with this or you want me to guide you.

**Comment by adrien-n** [comment]
Thank you for that commit and sorry for the delay. That's fine with me.

I should have no problem doing the transfer but I have to do it through OVH's interface obviously. As far as I can tell, it simply asks me for the new owner's mail address. Can you give one to me?

Also, I've decided not to change the configuration of the domain myself because I think it makes more sense to let the new owner do it at once the way they see fit.

**Comment by elieux** [comment]
If you mean e-mail, it's on the commit.  If you mean postal, can we use a private channel somewhere?

**Comment by lazka** [comment]
@adrien-n ping

**Comment by adrien-n** [comment]
@elieux Check your e-mails. :)

**Comment by elieux** [comment]
Replied.

**Comment by elieux** [comment]
In transfer. They say it can take 5 days.

**Comment by adrien-n** [comment]
It's quite probably part of the safety mechanisms that are set up in
order to prevent abusive domain transfers: I got an e-mail with a link
to deny the transfer along with a timelimit to do so.

**Comment by elieux** [comment]
@adrien-n, okay, transferred.

I wouldn't like to point the domain to different name servers until I'm sure we didn't forget anything.  Are there any other interesting records beside *www* in the zone?

Regarding the website, we're kind of discussing what to replace it with, but if you want to have it off your plate ASAP, I can do that.

**Comment by adrien-n** [comment]
There's nothing besides the web stuff.

As for the website, I'm fine with keeping it running for now. There's
absolutely no hurry there.

**Comment by lhmouse** [comment]
At the moment this repo contains a [CNAME with the value `www.mingw-w64.net`](https://github.com/mingw-w64/mingw-w64.github.io/blob/41a96ff29e53e65a24f2557c1443863a68b3671b/CNAME). So we're having two distinct websites: .net resolves to this GitHub Pages, and .org resolves to the old Doku Wiki.

Ideally I would like to have .org point to this site (which requires updating the CNAME file).

**Comment by lazka** [comment]
> Ideally I would like to have .org point to this site (which requires updating the CNAME file).

this is handled here btw: https://github.com/mingw-w64/mingw-w64.github.io/blob/92ab32c512034dceff1dea0d22798bac0687c552/.github/workflows/main.yml#L63

**Comment by lhmouse** [comment]
> this is handled here btw: https://github.com/mingw-w64/mingw-w64.github.io/blob/92ab32c512034dceff1dea0d22798bac0687c552/.github/workflows/main.yml#L63

Yes I know that. The .org domain has since long ago been our signboard, so pointing it to GitHub Pages where we accept PRs would be nice. BTW information on the [Download](http://mingw-w64.org/doku.php/download) page has been out of sync for years (it mentions nothing about 7.x+) and I really hope somebody can keep it up to date.

**Comment by elieux** [comment]
We were talking with nightstrike on IRC about moving the website back to SF.net, so I haven't taken any action in DNS yet.

**Comment by lazka** [comment]
> We were talking with nightstrike on IRC about moving the website back to SF.net, so I haven't taken any action in DNS yet.

I'm of course biased here, but can't we switch multiple times if needed?

**Comment by elieux** [comment]
Domains redirected for now.  I'm kind of locked out of IRC now.  I'll try to get back to the discussion later this week.

**Comment by lazka** [comment]
can anyone with admin rights of this project go to settings>pages and enable "enforce https"?

**Comment by jon-y** [comment]
Done.

**Comment by lazka** [comment]
@elieux changed the DNS yesterday and set up the redirects, so this is done now

thanks @adrien-n for you work - if there is anything you need or want to see regarding the website, let us know.
