### ISSUE TITLE
MinGW-w64-builds is now publishing releases at GitHub

### ISSUE THREAD

**Issue by Guyutongxue** [mingw-w64/mingw-w64.github.io#16]
GitHub repo [niXman/mingw-builds-binaries](https://github.com/niXman/mingw-builds-binaries) is now holding MinGW-w64-builds with latest version of both MinGW runtime and GCC. The owner of the repo has also claimed that it's an official build (see niXman/mingw-builds-binaries#5).

So I'd suggest updating the download URL and version table for MinGW-W64-builds in [downloads.md](https://github.com/mingw-w64/mingw-w64.github.io/blob/source/web/downloads.md). If that's OK, I can make a PR later.

**Comment by Biswa96** [comment]
Feel free to add the links in the documentation.
