### ISSUE TITLE
Mention https://winlibs.com/ on https://www.mingw-w64.org/

### ISSUE THREAD

**Issue by brechtsanders** [mingw-w64/mingw-w64.github.io#24]
I have been offering standalone native Windows builds of the latest MinGW-w64 for a while now on https://winlibs.com/
By now quite a community is using these builds.
Would you consider mentioning https://winlibs.com/ on https://www.mingw-w64.org/ ?

**Comment by lhmouse** [comment]
Hello, Brecht, nice to meet you again.

We accept Pull Requests here, so please create one for winlibs.
All download links are on <https://github.com/mingw-w64/mingw-w64.github.io/blob/source/web/downloads.md>.

**Comment by lazka** [comment]
-> #25
