### ISSUE TITLE
mingw32-make.exe  troubles on github ci

### ISSUE THREAD

**Issue by mu578** [mingw-w64/mingw-w64.github.io#38]
Hello, I have two projects using the exact same set of makefiles one just build fine the other one trigger errors on a single ruleset ; I went checking for all sort of things like space, bad characters ; nothing ; all sources are ascii cleared ; all filenames ok 

here reference builds:

https://github.com/mu578/mu0/actions/runs/5165919329/jobs/9305715828
https://github.com/mu578/mu8/actions/runs/5165936223/jobs/9305740260

```

/usr/bin/sh: -c: line 3: syntax error: unexpected end of file
[170](https://github.com/mu578/mu8/actions/runs/5165936223/jobs/9305740260#step:4:171)
mingw32-make: [D:/a/mu8/mu8/mu0/mk/inc/mu0_ruleset.mk:77: rule_linker_cmds] Error 2 (ignored)
[171](https://github.com/mu578/mu8/actions/runs/5165936223/jobs/9305740260#step:4:172)
/usr/bin/sh: -c: line 13: syntax error: unexpected end of file
[172](https://github.com/mu578/mu8/actions/runs/5165936223/jobs/9305740260#step:4:173)
mingw32-make: [D:/a/mu8/mu8/mu0/mk/inc/mu0_ruleset.mk:78: rule_linker_cmds] Error 2 (ignored)
[173](https://github.com/mu578/mu8/actions/runs/5165936223/jobs/9305740260#step:4:174)
[mingw64_nt-10.0-20348-x86_64] Archive : mu8 <= libmu8.a
[174](https://github.com/mu578/mu8/actions/runs/5165936223/jobs/9305740260#step:4:175)
/usr/bin/sh: -c: line 3: syntax error: unexpected end of file
[175](https://github.com/mu578/mu8/actions/runs/5165936223/jobs/9305740260#step:4:176)
mingw32-make: [D:/a/mu8/mu8/mu0/mk/inc/mu0_ruleset.mk:49: rule_static] Error 2 (ignored)

```

if any clue ; welcome ; I also tried to reduce the number of files thinking about some argument list length or memory issues ; nothing ; so far as it is the same exact file ; it doesn't make any sense to me.

Is it an installation problem on some machines? sorry ; this is website ; wrong place ; but still ? is anyone ever experienced such?

**Comment by Biswa96** [comment]
Where is the log/link of failed build?

**Comment by mu578** [comment]
in second one under distcheck. It is to compare between both which are using the exact same makefile include.

**Comment by Biswa96** [comment]
It seems that you are using msys2 in CI. We're probably in wrong repository.

Have you tried to use the msys2 make i.e. /usr/bin/make ? mingw32-make is not used generally and less tested.

**Comment by mu578** [comment]
so no, that's argument console length issues ; can't fix windows even with the all the best wishes in the world ; this thing has been driven and architected by an embodiment of mediocrity and such since day one; case close.

so the shell gets truncated memory to deal with. I shortened all paths to relatives ; and it auto-magically disappear.

**Comment by mu578** [comment]
so case close; windows should be cancelled by anyone.

**Comment by lhmouse** [comment]
Not sure about `mingw32-make` but I suspect it invokes `cmd` for recipes, like `make` which invokes a shell? For one single command line, cmd has a length limit of 8K characters which is shorter than the NT syscall limit (32K) and is even shorter than bash (a few megabytes).

**Comment by mu578** [comment]
@lhmouse yeah we already figured out. Like it is an excuse.
