### ISSUE TITLE
gdb has commandline encoding problem

### ISSUE THREAD

**Issue by TsXor** [mingw-w64/mingw-w64.github.io#47]
```
>gdb --version
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I used the following code to get a wargv in a GUI application.
```c++
static struct MyArgsW {
    wchar_t* basestr;
    int argc;
    wchar_t** argv;
    MyArgsW() {
        setlocale(LC_ALL, "");
        this->basestr = GetCommandLineW();
        this->argv = CommandLineToArgvW(this->basestr, &this->argc);
    }
    ~MyArgsW() {
        LocalFree(this->argv);
    }
} wargs;
```

However, when I launched the program with the following arguments (in vscode debug), it could not behave normally and will give wrong number of argc.
When used without gdb, it does what it should do.
```json
            "args": [
                "--userdata-path", "E:\\Users\\23Xor\\Desktop\\OpenWebview2Window-ng\\dist\\bin\\x64\\webdata",
                "--navigate-url", "https://www.baidu.com",
                "--window-title", "百度一下",
                "--tray-control"
            ],
```

Here is the part of the memory of commandline got by `GetCommandLineW`.
![21：53：59](https://github.com/mingw-w64/mingw-w64.github.io/assets/74352334/646276ee-e5d9-4a98-81df-723d419ae35a)

We can see that "百度一下" was encoded to the following:
![21：57：21](https://github.com/mingw-w64/mingw-w64.github.io/assets/74352334/063adfa6-d2ef-4227-a3ce-c0cbe5caecb7)

It seem to be an encoding problem, so I did an experiment to make sure.
```
百度一下
(encode with UTF-8)--->
\xE799BE\xE5BAA6\xE4B880\xE4B88B
(decode with GB2312, the ANSI codepage of my environment)--->
鐧惧害涓€涓?
(encode with UTF-16)--->
\u2794\uE760\uB35B\u936D\uAC20\u936D\u3F00
```
So let me guess, gdb give the commandline in UTF-8 encoding, but actually commandline is interpreted with ANSI encoding, and converted to UTF-16 encoding.

**Comment by Biswa96** [comment]
Why did you report gdb issue in mingw-w64 repository? Also try to use latest gdb version 13.2.

**Comment by lhmouse** [comment]
Not our bug. Read this first: https://github.com/msys2/MINGW-packages/issues/17398

**Comment by TsXor** [comment]
> Not our bug. Read this first: [msys2/MINGW-packages#17398](https://github.com/msys2/MINGW-packages/issues/17398)

我认为是，您提到的这个issue的问题是gdb在向控制台输出的时候使用的是UTF-8编码，但是控制台默认在不`chcp 65001`的情况下是按照ANSI解读并显示造成的。其中提到的解决方法`SetConsoleOutputCP(65001)`就是使`控制台编码 == UTF-8`，从而使解读正确，能正常显示。

但是，依照[我的另一个实验](https://zhuanlan.zhihu.com/p/646700079)，在Windows自己正常启动程序的情况下，程序的命令行都是按ANSI编码输入的，同时这个行为不是chcp能改变的。

**Comment by lhmouse** [comment]
> 但是，依照[我的另一个实验](https://zhuanlan.zhihu.com/p/646700079)，在Windows自己正常启动程序的情况下，程序的命令行都是按ANSI编码输入的，同时这个行为不是chcp能改变的。

`argv` 的解析并不由 mingw-w64 负责。MSVCRT 的时代这是一个库函数 <https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-crt/crt/crtexe.c#L141>；但是 UCRT 开始似乎变成了一个不知为何预解析好的变量，导出了一个函数取它的地址 <https://github.com/mingw-w64/mingw-w64/blob/024035cfd9059ebd39d95ab22b009ef3b88b4040/mingw-w64-crt/crt/ucrtbase_compat.c#L67>。这些东西理所当然地不受 console CP 的影响，因为不涉及 I/O，并且都是黑盒。无能为力，如果你觉得是个 bug，请报告给微软。

**Comment by TsXor** [comment]
close this and goto gdb

**Comment by lhmouse** [comment]
Also see this:  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108865
