### ISSUE TITLE
wcstok() defined differently in string.h and wchar.h for UCRT

### ISSUE THREAD

**Issue by brechtsanders** [mingw-w64/mingw-w64.github.io#7]
When using a UCRT build of MinGW-w64 9.0.0 (see my personal builds at https://winlibs.com/) `wcstok()` seems to be defined differently in `string.h` and `wchar.h`.

`string.h` defines `wcstok()` with 2 arguments:
```c
  wchar_t *__cdecl wcstok(wchar_t * __restrict__ _Str,const wchar_t * __restrict__ _Delim) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
```
`wchar.h` defines `wcstok()` with 3 arguments if `_UCRT` is defined:
```c
#if defined(_UCRT)
  wchar_t *__cdecl wcstok(wchar_t * __restrict__ _Str,const wchar_t * __restrict__ _Delim,wchar_t **_Ptr) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
#else
  wchar_t *__cdecl wcstok(wchar_t * __restrict__ _Str,const wchar_t * __restrict__ _Delim) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
#endif
```

This is giving me a lot of trouble with the [ACE](http://www.dre.vanderbilt.edu/~schmidt/ACE.html) library when building [YARP](http://www.yarp.it/) with UCRT.

**Comment by Biswa96** [comment]
This issue was probably fixes in https://github.com/mingw-w64/mingw-w64/commit/40134887fb81f5be451b5c4c92dc1e0372f08b68 commit.
